server.port=8082

# ??????? ?? ????? ?? ?????? ???? (??????? ???? ? school_db ??? school_inventory)
spring.datasource.url=jdbc:postgresql://localhost:5432/school_db?stringtype=unspecified
spring.datasource.username=admin
spring.datasource.password=password123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ?????? ?? Hibernate ?? ????? Postgres ???????? ??? Java
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=cb7ad4a0278e03
spring.mail.password=81de0621324363
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true