server.port=8082

# ??????? ?? ????? ?? ?????? ???? (??????? ???? ? school_db ??? school_inventory)
spring.datasource.url=jdbc:postgresql://localhost:5432/school_db?stringtype=unspecified
spring.datasource.username=admin
spring.datasource.password=password123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ?????? ?? Hibernate ?? ????? Postgres ???????? ??? Java
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SMTP ?????? ?? Hostinger (???? 587 ???????? STARTTLS)
spring.mail.host=smtp.hostinger.com
spring.mail.port=587
spring.mail.username=homelander@bgtulk.dev
spring.mail.password=Homelander_321

# ???????? ? ????????? ?? ???? 587
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ???????? ??? ?????????? ???? ??? ????, ?????? ?? ?????? ?? ???? 587:
# spring.mail.properties.mail.smtp.socketFactory.port=465
# spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory

spring.mail.default-encoding=UTF-8

# Low stock alert threshold
inventory.low-stock.threshold=2